name: test-production-apps-with-cypress
root: <%= Dir.pwd %>

windows:
  - frontend:
      layout: main-vertical
      panes:
        - vim README.md
        - npm run start
        - npm run test
        - npm run cypress
        -

